### ISSUE TITLE
How to add a text box to the OpenWorm muscle model sample?

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.samples#23]
We noticed the new OpenWorm muscle model geppetto sample is on live and had a chat about it today (check it out in [the video of the hangout](https://www.youtube.com/watch?v=3KApBmFa6WY#t=2055), conversation starts at 34:20)!  Congrats on getting this out.  

First question would be, having a look at the [Geppetto.xml for this](https://github.com/openworm/org.geppetto.samples/blob/development/LEMS/MuscleModel/GEPPETTO.xml).  If folks want to add a text box that has an explanation of this, how can this be done.  A search of the [documentation about widgets](http://docs.geppetto.org/en/latest/usingwidgets.html) doesn't make it clear how to add such a box.

**Comment by tarelli** [comment]
This is the culpable http://docs.geppetto.org/en/latest/popupW.html documentation ain't written yet :)
Adding the following will create a widget to put there a description.
```
G.addWidget(Widgets.POPUP);
Popup1.setMessage("Muscle model description");
Popup1.setName("Description");
```
As for the "cylinder" and "sphere" geometries they are coming from the NeuroML, see this for the cylinder: https://github.com/openworm/muscle_model/blob/master/NeuroML2/SingleCompMuscle.cell.nml#L13

As for the sphere it's an IAF cell without morphology that Geppetto represents as a Sphere.

**Comment by slarson** [comment]
Okay thanks.  I've added a pull request to improve the documentation:

https://github.com/openworm/org.geppetto.docs/pull/14
