### ISSUE TITLE
How to include more model structure in the tree visualizer of the OpenWorm muscle model?

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.samples#24]
In having a look at the new OpenWorm muscle model sample in [today's meeting](https://www.youtube.com/watch?v=3KApBmFa6WY#t=2055) (conversation starts at 34:20), We noticed that many of the rows in the tree visualizer don't actually expand when clicked.  Is there a way that the sample can be modified to either remove these empty rows, or to populate them by default?  Looking up the [docs for the TreeVisualizer](http://docs.geppetto.org/en/latest/treevisualizerW.html) unfortunately leads to a blank page....

**Comment by tarelli** [comment]
[This(https://github.com/openworm/org.geppetto.samples/blob/development/LEMS/MuscleModel/script.js#L1) line that I just added does it.
@adrianq when you have a chance can you improve the docs on the model tree stuff? :)

**Comment by slarson** [comment]
OK thanks.  I've started a pull request to get the tree visualizer docs going:

https://github.com/openworm/org.geppetto.docs/pull/17

**Comment by adrianq** [comment]
@tarelli I will write the docs for the widgets as soon as I have some spare time....but you know better than me that we have more than enough on our plates at the moment :)

**Comment by tarelli** [comment]
@adrianq of course, I do know ;)

**Comment by tarelli** [comment]
Improved after @slarson start: http://docs.geppetto.org/en/latest/treevisualizerW.html
