### ISSUE TITLE
How to edit the visualization of the OpenWorm muscle model?

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.samples#25]
Looking at the 3D representation of the muscle model, it seems like it should be closer to the camera and probably rotated 90 degrees.  How would a contributor go about making those changes to [the model file](https://raw.githubusercontent.com/openworm/org.geppetto.samples/development/LEMS/MuscleModel/GEPPETTO.xml)?  I can't find anything searching the docs for how to set up or modify the visualization of the neuron or the muscle.

**Comment by tarelli** [comment]
When you use the buttons to navigate the camera a command is sent to the console, those same commands can be added to the script file.
See [these](https://github.com/openworm/org.geppetto.samples/blob/master/NeuroML/ACnet2/script.js#L8) lines from another example. Unfortunately the movement is still relative and absolute coordinates can't be yet specified, nor the position of the camera can be yet read from whatever you have on the screen. @gidili was working on this some time ago but API commands with relative increments is as far as he got.

**Comment by slarson** [comment]
Okay, I'm seeing the following issues relevant to this:

openworm/org.geppetto#349
openworm/org.geppetto#160

I'll comment further over there.

Another solution to this in the short term would be to change the coordinates in the LEMS file itself right?  In theory if we changed the coordinates here, we could get it to show up closer to the camera?

https://github.com/openworm/muscle_model/blob/master/NeuroML2/SingleCompMuscle.cell.nml#L13

**Comment by pgleeson** [comment]
Might be better for now just to change the location of these cells in the network file here: https://github.com/openworm/muscle_model/blob/master/NeuroML2/NeuronMuscle.net.nml#L26
